apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lancium-provisioner-log-pvc
  namespace: osg-opportunistic
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
